// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPYHeTGdAr4c_ByxTcg0iJ9Djw0E6D1PI',
    appId: '1:884936670382:web:48bee9bc831d5b3312813f',
    messagingSenderId: '884936670382',
    projectId: 'croma-techs',
    authDomain: 'croma-techs.firebaseapp.com',
    storageBucket: 'croma-techs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLWlR2Krwzs_u58ePCAXGGdVb6DGQKgpk',
    appId: '1:884936670382:android:9806fe7b49ea1c7712813f',
    messagingSenderId: '884936670382',
    projectId: 'croma-techs',
    storageBucket: 'croma-techs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYnl-v2U9gIVPqrYaj0HFiPWqePjIjoI',
    appId: '1:884936670382:ios:2d29423d4e2c199612813f',
    messagingSenderId: '884936670382',
    projectId: 'croma-techs',
    storageBucket: 'croma-techs.appspot.com',
    androidClientId: '884936670382-9j65sgueat3qqmv7sk4mkok70ma6ju0v.apps.googleusercontent.com',
    iosClientId: '884936670382-mag3hf67ddjs7c4966h64ti6r53pma5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.cromaTechs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiYnl-v2U9gIVPqrYaj0HFiPWqePjIjoI',
    appId: '1:884936670382:ios:5e55ef06fc73138f12813f',
    messagingSenderId: '884936670382',
    projectId: 'croma-techs',
    storageBucket: 'croma-techs.appspot.com',
    androidClientId: '884936670382-9j65sgueat3qqmv7sk4mkok70ma6ju0v.apps.googleusercontent.com',
    iosClientId: '884936670382-62c73r638bdqds7tlbf1bgafmfbbkm89.apps.googleusercontent.com',
    iosBundleId: 'com.example.cromaTechs.RunnerTests',
  );
}
